/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prestamo;

/**
 *
 * @author Mario
 */

import java.awt.Color;

import usuario.StatusUsuario;

public class PrestamosMora extends javax.swing.JFrame {
    private static PrestamosMora moraGUI;
    
    private StatusUsuario userStatus;

    /**
     * Creates new form PrestamoRegistro
     */
    private PrestamosMora() {
        initComponents();
    }
    
    public static void mount() {
        moraGUI = new PrestamosMora();
        moraGUI.setVisible(true);
    }
    
    public static void unmount(){
        moraGUI.setVisible(false);
        moraGUI.dispose();
        moraGUI = null;
    }
    
    private static void goBack() {
        unmount();
        MenuPrestamos.mount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlInputs = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblReturnFee = new javax.swing.JLabel();
        txtReturnFee = new javax.swing.JTextField();
        lblUserExists = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLibros = new javax.swing.JLabel();
        txtLibros = new javax.swing.JTextField();
        lblObras = new javax.swing.JLabel();
        txtObras = new javax.swing.JTextField();
        lblRevistas = new javax.swing.JLabel();
        txtRevistas = new javax.swing.JTextField();
        lblCds = new javax.swing.JLabel();
        txtCds = new javax.swing.JTextField();
        lblTesis = new javax.swing.JLabel();
        txtTesis = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        pnlBottomButtons = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Consulta de Mora");

        pnlInputs.setBackground(new java.awt.Color(204, 255, 255));

        lblUsername.setText("Usuario:");

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        lblReturnFee.setLabelFor(txtReturnFee);
        lblReturnFee.setText("Mora total:");

        txtReturnFee.setEditable(false);

        lblUserExists.setText(" ");

        jLabel1.setText("Préstamos con mora:");

        lblLibros.setText("Libros:");

        txtLibros.setEditable(false);

        lblObras.setText("Obras:");

        txtObras.setEditable(false);

        lblRevistas.setText("Revistas:");

        txtRevistas.setEditable(false);

        lblCds.setText("CDs:");

        txtCds.setEditable(false);

        lblTesis.setText("Tesis:");

        txtTesis.setEditable(false);

        lblStatus.setText(" ");

        lblQuantity.setText("0");

        javax.swing.GroupLayout pnlInputsLayout = new javax.swing.GroupLayout(pnlInputs);
        pnlInputs.setLayout(pnlInputsLayout);
        pnlInputsLayout.setHorizontalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLibros)
                            .addComponent(txtLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblObras))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRevistas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRevistas))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCds)
                            .addComponent(txtCds, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTesis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTesis)))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantity))
                    .addComponent(txtReturnFee, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReturnFee)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserExists)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        pnlInputsLayout.setVerticalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(lblUserExists))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblQuantity))
                .addGap(18, 18, 18)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRevistas)
                            .addComponent(lblCds)
                            .addComponent(lblTesis)
                            .addComponent(lblObras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRevistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblLibros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblReturnFee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReturnFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pnlBottomButtons.setBackground(new java.awt.Color(204, 255, 255));

        btnCancel.setText("Regresar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomButtonsLayout = new javax.swing.GroupLayout(pnlBottomButtons);
        pnlBottomButtons.setLayout(pnlBottomButtonsLayout);
        pnlBottomButtonsLayout.setHorizontalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomButtonsLayout.setVerticalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottomButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlBottomButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        String username = this.txtUsername.getText();
        this.userStatus = StatusUsuario.usuarioStatus(username);
        if (this.userStatus != null) {
            this.lblUserExists.setText("✔");
            this.lblUserExists.setForeground(Color.green);
            
            this.lblQuantity.setText(this.userStatus.moraAcumulada.get("total")[0]);
            
            this.txtLibros.setText(this.userStatus.moraAcumulada.get("libros")[0]);
            if (this.userStatus.moraAcumulada.get("libros")[0].equals("0"))
                this.txtLibros.setBackground(Color.green);
            else
                this.txtLibros.setBackground(Color.red);
            
            this.txtObras.setText(this.userStatus.moraAcumulada.get("obras")[0]);
            if (this.userStatus.moraAcumulada.get("obras")[0].equals("0"))
                this.txtObras.setBackground(Color.green);
            else
                this.txtObras.setBackground(Color.red);
            
            this.txtRevistas.setText(this.userStatus.moraAcumulada.get("revistas")[0]);
            if (this.userStatus.moraAcumulada.get("revistas")[0].equals("0"))
                this.txtRevistas.setBackground(Color.green);
            else
                this.txtRevistas.setBackground(Color.red);
            
            this.txtCds.setText(this.userStatus.moraAcumulada.get("cds")[0]);
            if (this.userStatus.moraAcumulada.get("cds")[0].equals("0"))
                this.txtCds.setBackground(Color.green);
            else
                this.txtCds.setBackground(Color.red);
            
            this.txtTesis.setText(this.userStatus.moraAcumulada.get("tesis")[0]);
            if (this.userStatus.moraAcumulada.get("tesis")[0].equals("0"))
                this.txtTesis.setBackground(Color.green);
            else
                this.txtTesis.setBackground(Color.red);
            
            this.txtReturnFee.setText(this.userStatus.moraAcumulada.get("total")[1]);
            if (this.userStatus.moraAcumulada.get("total")[0].equals("0")) {
                this.lblStatus.setText("Este usuario NO posee mora!");
                this.lblStatus.setForeground(Color.green);
                this.txtReturnFee.setBackground(Color.green);
            } else {
                this.lblStatus.setText("Este usuario SI posee mora!");
                this.lblStatus.setForeground(Color.red);
                this.txtReturnFee.setBackground(Color.red);
            }
        } else {
            this.lblUserExists.setText("❌");
            this.lblUserExists.setForeground(Color.red);
            
            this.lblStatus.setText("");
            this.lblStatus.setForeground(Color.black);
            this.lblQuantity.setText("0");
            this.txtLibros.setText("");
            this.txtLibros.setBackground(Color.LIGHT_GRAY);
            this.txtObras.setText("");
            this.txtObras.setBackground(Color.LIGHT_GRAY);
            this.txtRevistas.setText("");
            this.txtRevistas.setBackground(Color.LIGHT_GRAY);
            this.txtCds.setText("");
            this.txtCds.setBackground(Color.LIGHT_GRAY);
            this.txtTesis.setText("");
            this.txtTesis.setBackground(Color.LIGHT_GRAY);
            this.txtReturnFee.setText("");
            this.txtReturnFee.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        goBack();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCds;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JLabel lblObras;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReturnFee;
    private javax.swing.JLabel lblRevistas;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTesis;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserExists;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBottomButtons;
    private javax.swing.JPanel pnlInputs;
    private javax.swing.JTextField txtCds;
    private javax.swing.JTextField txtLibros;
    private javax.swing.JTextField txtObras;
    private javax.swing.JTextField txtReturnFee;
    private javax.swing.JTextField txtRevistas;
    private javax.swing.JTextField txtTesis;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
