/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prestamo;

/**
 *
 * @author Mario
 */

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.List;

import usuario.StatusUsuario;

public class PrestamoDevolucion extends javax.swing.JFrame {
    private static PrestamoDevolucion devolucionGUI;
    
    private StatusUsuario userStatus;
    private String itemCategory;
    private String prestamoId;
    private List<String[]> prestamos;

    /**
     * Creates new form PrestamoRegistro
     */
    private PrestamoDevolucion() {
        initComponents();
    }
    
    public static void mount() {
        devolucionGUI = new PrestamoDevolucion();
        devolucionGUI.setVisible(true);
    }
    
    public static void unmount(){
        devolucionGUI.setVisible(false);
        devolucionGUI.dispose();
        devolucionGUI = null;
    }
    
    private static void goBack() {
        unmount();
        MenuPrestamos.mount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlInputs = new javax.swing.JPanel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblItemId = new javax.swing.JLabel();
        cmbItemId = new javax.swing.JComboBox<>();
        txtItemDesc = new javax.swing.JTextField();
        lblItemDesc = new javax.swing.JLabel();
        lblReturnFee = new javax.swing.JLabel();
        txtReturnFee = new javax.swing.JTextField();
        lblUserExists = new javax.swing.JLabel();
        lblRentalDate = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        lblReturnDate = new javax.swing.JLabel();
        txtReturnDate = new javax.swing.JTextField();
        pnlBottomButtons = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Devolución de Préstamo");

        pnlInputs.setBackground(new java.awt.Color(204, 255, 255));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libros", "Obras", "Revistas", "CDs", "Tesis" }));
        cmbCategory.setSelectedIndex(-1);
        cmbCategory.setToolTipText("");
        cmbCategory.setEnabled(false);
        cmbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryItemStateChanged(evt);
            }
        });

        lblCategory.setLabelFor(cmbCategory);
        lblCategory.setText("Categoría:");

        lblUsername.setText("Usuario:");

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        lblItemId.setLabelFor(cmbItemId);
        lblItemId.setText("Objeto a devolver:");

        cmbItemId.setEditable(true);
        cmbItemId.setEnabled(false);
        cmbItemId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemIdItemStateChanged(evt);
            }
        });

        txtItemDesc.setEditable(false);

        lblItemDesc.setLabelFor(txtItemDesc);
        lblItemDesc.setText("Descripción del ítem:");

        lblReturnFee.setLabelFor(txtReturnFee);
        lblReturnFee.setText("Mora total:");

        txtReturnFee.setEditable(false);

        lblUserExists.setText(" ");

        lblRentalDate.setLabelFor(txtRentalDate);
        lblRentalDate.setText("Fecha de préstamo:");

        txtRentalDate.setEditable(false);

        lblReturnDate.setLabelFor(txtReturnDate);
        lblReturnDate.setText("Fecha límite de devolución:");

        txtReturnDate.setEditable(false);

        javax.swing.GroupLayout pnlInputsLayout = new javax.swing.GroupLayout(pnlInputs);
        pnlInputs.setLayout(pnlInputsLayout);
        pnlInputsLayout.setHorizontalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblItemDesc)
                    .addComponent(txtItemDesc)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbItemId, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputsLayout.createSequentialGroup()
                                    .addComponent(lblUsername)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblUserExists)))
                            .addComponent(lblItemId))
                        .addGap(60, 60, 60)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategory)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReturnFee)
                            .addComponent(txtReturnFee, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRentalDate))
                        .addGap(60, 60, 60)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReturnDate)
                            .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInputsLayout.setVerticalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(lblUsername)
                    .addComponent(lblUserExists))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemId)
                    .addComponent(lblReturnFee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturnFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItemDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRentalDate)
                    .addComponent(lblReturnDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlBottomButtons.setBackground(new java.awt.Color(204, 255, 255));

        btnRegister.setText("Devolver");
        btnRegister.setEnabled(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomButtonsLayout = new javax.swing.GroupLayout(pnlBottomButtons);
        pnlBottomButtons.setLayout(pnlBottomButtonsLayout);
        pnlBottomButtonsLayout.setHorizontalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(54, 54, 54)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomButtonsLayout.setVerticalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(pnlBottomButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlBottomButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        String username = this.txtUsername.getText();
        this.userStatus = StatusUsuario.usuarioStatus(username);
        if (this.userStatus != null) {
            this.lblUserExists.setText("✔");
            this.lblUserExists.setForeground(Color.green);
            this.cmbCategory.setEnabled(true);
        } else {
            this.lblUserExists.setText("❌");
            this.lblUserExists.setForeground(Color.red);
            this.cmbCategory.setEnabled(false);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void cmbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryItemStateChanged
        if (this.cmbCategory.getSelectedIndex() < 0) {
            this.cmbItemId.setEnabled(false);
            return;
        }
        
        this.itemCategory = this.cmbCategory.getSelectedItem().toString();
        
        this.cmbItemId.removeAllItems();
        this.prestamos = Prestamo.prestamosUsuarioCategoria(this.userStatus.nombre, this.itemCategory.toLowerCase());
        this.prestamos.forEach((prestamo) -> {
            this.cmbItemId.addItem(prestamo[1]);
        });
        this.cmbItemId.setEnabled(true);
    }//GEN-LAST:event_cmbCategoryItemStateChanged

    private void cmbItemIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemIdItemStateChanged
        int selected = this.cmbItemId.getSelectedIndex();
        
        if (selected < 0) {
            this.prestamoId = null;
            this.txtReturnFee.setText("");
            this.txtReturnFee.setBackground(Color.gray);
            this.txtItemDesc.setText("");
            this.txtRentalDate.setText("");
            this.txtReturnDate.setText("");
            this.btnRegister.setEnabled(false);
            return;
        }
        
        String[] prestamo = this.prestamos.get(selected);
        
        this.prestamoId = prestamo[0];
        
        this.txtReturnFee.setText(prestamo[4]);
        if (prestamo[4].equals("$0.0"))
            this.txtReturnFee.setBackground(Color.green);
        else
            this.txtReturnFee.setBackground(Color.red);
        this.txtItemDesc.setText(prestamo[1]);
        this.txtRentalDate.setText(prestamo[2]);
        this.txtReturnDate.setText(prestamo[3]);
        this.btnRegister.setEnabled(true);
    }//GEN-LAST:event_cmbItemIdItemStateChanged

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar este registro?", "Confirmación", 0);
        if (confirm != 0)
            return;
        
        if (Prestamo.devolver(this.itemCategory, this.prestamoId)) {
            unmount();
            mount();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        goBack();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbItemId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblItemDesc;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblRentalDate;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblReturnFee;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserExists;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBottomButtons;
    private javax.swing.JPanel pnlInputs;
    private javax.swing.JTextField txtItemDesc;
    private javax.swing.JTextField txtRentalDate;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtReturnFee;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
