/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prestamo;

/**
 *
 * @author Mario
 */

import java.awt.Color;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;

import items.Consulta;
import usuario.StatusUsuario;
import utilidades.Fechas;

public class PrestamoRegistro extends javax.swing.JFrame {
    private static PrestamoRegistro prestamoGUI;
    
    private String itemCategory;
    private String itemId;
    private StatusUsuario userStatus;
    private String returnDate;

    /**
     * Creates new form PrestamoRegistro
     */
    private PrestamoRegistro() {
        initComponents();
    }
    
    public static void mount() {
        prestamoGUI = new PrestamoRegistro();
        prestamoGUI.setVisible(true);
    }
    
    public static void unmount(){
        prestamoGUI.setVisible(false);
        prestamoGUI.dispose();
        prestamoGUI = null;
    }
    
    private static void goBack() {
        unmount();
        MenuPrestamos.mount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlInputs = new javax.swing.JPanel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblItemId = new javax.swing.JLabel();
        cmbItemId = new javax.swing.JComboBox<>();
        txtItemDesc = new javax.swing.JTextField();
        lblItemDesc = new javax.swing.JLabel();
        lblReturnDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtItemAvail = new javax.swing.JTextField();
        lblUserExists = new javax.swing.JLabel();
        lblUserHelper = new javax.swing.JLabel();
        lblDateHelper = new javax.swing.JLabel();
        txtReturnDate = new javax.swing.JTextField();
        pnlBottomButtons = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro de Préstamo");

        pnlInputs.setBackground(new java.awt.Color(204, 255, 255));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Obra", "Revista", "CD", "Tesis" }));
        cmbCategory.setSelectedIndex(-1);
        cmbCategory.setToolTipText("");
        cmbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryItemStateChanged(evt);
            }
        });

        lblCategory.setLabelFor(cmbCategory);
        lblCategory.setText("Categoría:");

        lblUsername.setText("Usuario:");

        txtUsername.setEnabled(false);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        lblItemId.setLabelFor(cmbItemId);
        lblItemId.setText("ID de ítem:");

        cmbItemId.setEditable(true);
        cmbItemId.setEnabled(false);
        cmbItemId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemIdItemStateChanged(evt);
            }
        });

        txtItemDesc.setEditable(false);

        lblItemDesc.setLabelFor(txtItemDesc);
        lblItemDesc.setText("Descripción del ítem:");

        lblReturnDate.setLabelFor(txtReturnDate);
        lblReturnDate.setText("Fecha de devolución:");

        jLabel1.setText("Disponible:");

        txtItemAvail.setEditable(false);
        txtItemAvail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblUserHelper.setForeground(new java.awt.Color(235, 70, 52));
        lblUserHelper.setText(" ");

        lblDateHelper.setForeground(new java.awt.Color(52, 58, 235));
        lblDateHelper.setText(" ");

        txtReturnDate.setEditable(false);

        javax.swing.GroupLayout pnlInputsLayout = new javax.swing.GroupLayout(pnlInputs);
        pnlInputs.setLayout(pnlInputsLayout);
        pnlInputsLayout.setHorizontalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlInputsLayout.createSequentialGroup()
                            .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlInputsLayout.createSequentialGroup()
                                    .addComponent(lblCategory)
                                    .addGap(193, 193, 193))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputsLayout.createSequentialGroup()
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(60, 60, 60)))
                            .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblItemId)
                                .addComponent(cmbItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlInputsLayout.createSequentialGroup()
                            .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblItemDesc))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtItemAvail)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInputsLayout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUserExists)
                                .addGap(198, 198, 198))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInputsLayout.createSequentialGroup()
                                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(lblUserHelper))
                                .addGap(60, 60, 60)))
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReturnDate)
                            .addComponent(txtReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(lblDateHelper))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlInputsLayout.setVerticalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblItemId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemDesc)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblReturnDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(lblUserExists))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateHelper)
                    .addComponent(lblUserHelper))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnlBottomButtons.setBackground(new java.awt.Color(204, 255, 255));

        btnRegister.setText("Registrar");
        btnRegister.setEnabled(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomButtonsLayout = new javax.swing.GroupLayout(pnlBottomButtons);
        pnlBottomButtons.setLayout(pnlBottomButtonsLayout);
        pnlBottomButtonsLayout.setHorizontalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(54, 54, 54)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomButtonsLayout.setVerticalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlBottomButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlBottomButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryItemStateChanged
        this.itemCategory = this.cmbCategory.getSelectedItem().toString();

        String[] ids = null;
        switch (this.itemCategory) {
            case "Libro":
                ids = Consulta.idsCategoria(Consulta.Categoria.LIBROS);
                break;
            case "Obra":
                ids = Consulta.idsCategoria(Consulta.Categoria.OBRAS);
                break;
            case "Revista":
                ids = Consulta.idsCategoria(Consulta.Categoria.REVISTAS);
                break;
            case "CD":
                ids = Consulta.idsCategoria(Consulta.Categoria.CDS);
                break;
            case "Tesis":
                ids = Consulta.idsCategoria(Consulta.Categoria.TESIS);
                break;
            default:
                break;
        }

        this.cmbItemId.removeAllItems();
        if (ids != null && ids.length > 0) {
            for (String id : ids) {
                this.cmbItemId.addItem(id);
            }
            this.cmbItemId.setEnabled(true);
        } else {
            this.cmbItemId.setEnabled(false);
        }
    }//GEN-LAST:event_cmbCategoryItemStateChanged

    private void cmbItemIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemIdItemStateChanged
        if (this.cmbItemId.getSelectedIndex() < 0)
            return;
        
        this.itemId = this.cmbItemId.getSelectedItem().toString();
        
        String[] itemData = null;
        switch (this.itemCategory) {
            case "Libro":
                itemData = Consulta.librosDescriptiveStr(this.itemId);
                break;
            case "Obra":
                itemData = Consulta.obrasDescriptiveStr(this.itemId);
                break;
            case "Revista":
                itemData = Consulta.revistasDescriptiveStr(this.itemId);
                break;
            case "CD":
                itemData = Consulta.cdsDescriptiveStr(this.itemId);
                break;
            case "Tesis":
                itemData = Consulta.tesisDescriptiveStr(this.itemId);
                break;
            default:
                break;
        }
        
        if (itemData != null && itemData.length == 2) {
            this.txtItemDesc.setText(itemData[0]);
            if (itemData[1].equals("Si")) {
                this.txtItemAvail.setText("✔");
                this.txtItemAvail.setBackground(Color.green);
                this.txtUsername.setEnabled(true);
            } else if (itemData[1].equals("No")) {
                this.txtItemAvail.setText("❌");
                this.txtItemAvail.setBackground(Color.red);
                this.txtUsername.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmbItemIdItemStateChanged

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        String username = this.txtUsername.getText();
        this.userStatus = StatusUsuario.usuarioStatus(username);
        if (this.userStatus != null) {
            this.lblUserExists.setText("✔");
            this.lblUserExists.setForeground(Color.green);
            
            if (this.userStatus.tieneMora) {
                this.lblUserHelper.setText("Tiene mora pendiente!");
                return;
            } else if (this.userStatus.limiteExcedido) {
                this.lblUserHelper.setText("Límite de préstamos excedido!");
                return;
            } else {
                this.lblUserHelper.setText("");
            }
            
//            GENERATE RETURN DATE FOR THE USER
            this.lblDateHelper.setText("Máximo " + this.userStatus.maxDias + " días.");
            
            this.returnDate = Fechas.format(LocalDateTime.now().plusDays(this.userStatus.maxDias));
            this.txtReturnDate.setText(this.returnDate);
            this.txtReturnDate.setEnabled(true);
            this.btnRegister.setEnabled(true);
        } else {
            this.lblUserExists.setText("❌");
            this.lblUserExists.setForeground(Color.red);
            this.lblDateHelper.setText("");
            this.txtReturnDate.setText("");
            this.txtReturnDate.setEnabled(false);
            this.btnRegister.setEnabled(false);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar este registro?", "Confirmación", 0);
        if (confirm != 0)
            return;
        
        if (Prestamo.registrar(this.itemCategory, this.userStatus.userId, this.returnDate, this.itemId)) {
            unmount();
            mount();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        goBack();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbItemId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDateHelper;
    private javax.swing.JLabel lblItemDesc;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserExists;
    private javax.swing.JLabel lblUserHelper;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBottomButtons;
    private javax.swing.JPanel pnlInputs;
    private javax.swing.JTextField txtItemAvail;
    private javax.swing.JTextField txtItemDesc;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
