/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package registro;

/**
 *
 * @author Mario
 */

import java.awt.Color;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime; 
import javax.swing.JOptionPane;

import menu.Menu;
import consulta.Consulta;
import consulta.StatusUsuario;

public class PrestamoRegistro extends javax.swing.JFrame {
    private static PrestamoRegistro prestamoGUI;
    
    private String itemCategory;
    private String itemId;
    private boolean itemAvailable;
    private StatusUsuario userStatus;
    private String returnDate;

    /**
     * Creates new form PrestamoRegistro
     */
    private PrestamoRegistro() {
        initComponents();
    }
    
    public static void mount() {
        prestamoGUI = new PrestamoRegistro();
        prestamoGUI.setVisible(true);
    }
    
    public static void unmount(){
        prestamoGUI.setVisible(false);
        prestamoGUI.dispose();
        prestamoGUI = null;
    }
    
    private static void goBack() {
        unmount();
        Menu.mount();
    }
    
    public static String joinArray(Object[] arr, String delimiter) {
        StringBuilder sb = new StringBuilder();
        for (Object obj : arr)
                sb.append(obj.toString()).append(delimiter);
        return sb.substring(0, sb.length() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlInputs = new javax.swing.JPanel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblItemId = new javax.swing.JLabel();
        cmbItemId = new javax.swing.JComboBox<>();
        txtItemDesc = new javax.swing.JTextField();
        lblItemDesc = new javax.swing.JLabel();
        lblReturnDate = new javax.swing.JLabel();
        cmbReturnDate = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtItemAvail = new javax.swing.JTextField();
        lblUserExists = new javax.swing.JLabel();
        lblUserHelper = new javax.swing.JLabel();
        lblDateHelper = new javax.swing.JLabel();
        pnlBottomButtons = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro de préstamo");

        pnlInputs.setBackground(new java.awt.Color(204, 255, 255));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Obra", "Revista", "CD", "Tesis" }));
        cmbCategory.setSelectedIndex(-1);
        cmbCategory.setToolTipText("");
        cmbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryItemStateChanged(evt);
            }
        });

        lblCategory.setLabelFor(cmbCategory);
        lblCategory.setText("Categoría:");

        lblUsername.setText("Usuario:");

        txtUsername.setEnabled(false);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        lblItemId.setLabelFor(cmbItemId);
        lblItemId.setText("ID de ítem:");

        cmbItemId.setEditable(true);
        cmbItemId.setEnabled(false);
        cmbItemId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemIdItemStateChanged(evt);
            }
        });

        txtItemDesc.setEditable(false);

        lblItemDesc.setLabelFor(txtItemDesc);
        lblItemDesc.setText("Descripción del ítem:");

        lblReturnDate.setLabelFor(cmbReturnDate);
        lblReturnDate.setText("Fecha de devolución:");

        cmbReturnDate.setEnabled(false);
        cmbReturnDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbReturnDateItemStateChanged(evt);
            }
        });

        jLabel1.setText("Disponible:");

        txtItemAvail.setEditable(false);
        txtItemAvail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblUserHelper.setForeground(new java.awt.Color(235, 70, 52));

        javax.swing.GroupLayout pnlInputsLayout = new javax.swing.GroupLayout(pnlInputs);
        pnlInputs.setLayout(pnlInputsLayout);
        pnlInputsLayout.setHorizontalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategory))
                        .addGap(60, 60, 60)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemId)
                            .addComponent(cmbItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlInputsLayout.createSequentialGroup()
                                .addComponent(lblUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUserExists))
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(lblUserHelper))
                        .addGap(60, 60, 60)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReturnDate)
                            .addComponent(cmbReturnDate, 0, 184, Short.MAX_VALUE)
                            .addComponent(lblDateHelper)))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemDesc)
                            .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtItemAvail)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlInputsLayout.setVerticalGroup(
            pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputsLayout.createSequentialGroup()
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblItemId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemDesc)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addComponent(lblReturnDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInputsLayout.createSequentialGroup()
                        .addGroup(pnlInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(lblUserExists))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDateHelper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserHelper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlBottomButtons.setBackground(new java.awt.Color(204, 255, 255));

        btnRegister.setText("Registrar");
        btnRegister.setEnabled(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomButtonsLayout = new javax.swing.GroupLayout(pnlBottomButtons);
        pnlBottomButtons.setLayout(pnlBottomButtonsLayout);
        pnlBottomButtonsLayout.setHorizontalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(54, 54, 54)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomButtonsLayout.setVerticalGroup(
            pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlBottomButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnlBottomButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryItemStateChanged
        this.itemCategory = this.cmbCategory.getSelectedItem().toString();

        String[] ids = null;
        switch (this.itemCategory) {
            case "Libro":
                ids = Consulta.librosIds();
                break;
            case "Obra":
                ids = Consulta.obrasIds();
                break;
            case "Revista":
                ids = Consulta.revistasIds();
                break;
            case "CD":
                ids = Consulta.cdsIds();
                break;
            case "Tesis":
                ids = Consulta.tesisIds();
                break;
            default:
                break;
        }

        this.cmbItemId.removeAllItems();
        if (ids != null && ids.length > 0) {
            for (String id : ids) {
                this.cmbItemId.addItem(id);
            }
            this.cmbItemId.setEnabled(true);
        } else {
            this.cmbItemId.setEnabled(false);
        }
    }//GEN-LAST:event_cmbCategoryItemStateChanged

    private void cmbItemIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemIdItemStateChanged
        if (this.cmbItemId.getSelectedIndex() < 0)
            return;
        
        this.itemId = this.cmbItemId.getSelectedItem().toString();
        
        String[] itemData = null;
        switch (this.itemCategory) {
            case "Libro":
                itemData = Consulta.librosDescriptiveStr(this.itemId);
                break;
            case "Obra":
                itemData = Consulta.obrasDescriptiveStr(this.itemId);
                break;
            case "Revista":
                itemData = Consulta.revistasDescriptiveStr(this.itemId);
                break;
            case "CD":
                itemData = Consulta.cdsDescriptiveStr(this.itemId);
                break;
            case "Tesis":
                itemData = Consulta.tesisDescriptiveStr(this.itemId);
                break;
            default:
                break;
        }
        
        if (itemData != null && itemData.length == 2) {
            this.txtItemDesc.setText(itemData[0]);
            if (itemData[1].equals("Si")) {
                this.itemAvailable = true;
                this.txtItemAvail.setText("✔");
                this.txtItemAvail.setBackground(Color.green);
                this.txtUsername.setEnabled(true);
            } else if (itemData[1].equals("No")) {
                this.itemAvailable = false;
                this.txtItemAvail.setText("❌");
                this.txtItemAvail.setBackground(Color.red);
                this.txtUsername.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmbItemIdItemStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        goBack();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        String username = this.txtUsername.getText();
        this.userStatus = Consulta.usuarioStatus(username);
        if (this.userStatus != null) {
            this.lblUserExists.setText("✔");
            this.lblUserExists.setForeground(Color.green);
            
            if (!this.userStatus.puedePrestar) {
                this.lblUserHelper.setText("Límite de préstamos excedido!");
                return;
            } else {
                this.lblUserHelper.setText("");
            }
            
//            GENERATE AVAILABLE RETURN DATES FOR THE USER
            this.lblDateHelper.setText("Máximo " + this.userStatus.maxDias + " días.");
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDateTime now = LocalDateTime.now();
            for (int i = 0; i < this.userStatus.maxDias; i++) {
                this.cmbReturnDate.addItem(dtf.format(now.plusDays(i + 1)));
            }
            this.cmbReturnDate.setEnabled(true);
        } else {
            this.userStatus = null;
            this.lblUserExists.setText("❌");
            this.lblUserExists.setForeground(Color.red);
            this.lblDateHelper.setText("");
            this.cmbReturnDate.removeAllItems();
            this.cmbReturnDate.setEnabled(false);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void cmbReturnDateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbReturnDateItemStateChanged
        if (this.cmbReturnDate.getSelectedIndex() < 0) {
            this.btnRegister.setEnabled(false);
            return;
        }
        
        this.returnDate = this.cmbReturnDate.getSelectedItem().toString();
        
        this.btnRegister.setEnabled(true);
    }//GEN-LAST:event_cmbReturnDateItemStateChanged

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar este registro?", "Confirmación", 0);
        if (confirm != 0)
            return;
        
        if (Registro.prestamo(this.itemCategory, this.userStatus.userId, this.returnDate, this.itemId)) {
            unmount();
            mount();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbItemId;
    private javax.swing.JComboBox<String> cmbReturnDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDateHelper;
    private javax.swing.JLabel lblItemDesc;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblReturnDate;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUserExists;
    private javax.swing.JLabel lblUserHelper;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBottomButtons;
    private javax.swing.JPanel pnlInputs;
    private javax.swing.JTextField txtItemAvail;
    private javax.swing.JTextField txtItemDesc;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
